In [49]:
import numpy as np
import pandas as pd

df1 = pd.read_csv('customers.csv')
df2 = pd.read_csv('sales.csv')
df2

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [50]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         500 non-null    int64
 1   customer_rating  500 non-null    int64
dtypes: int64(2)
memory usage: 7.9 KB

In [51]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    str
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 39.2 KB

In [52]:
df1.shape

(500, 2)

In [53]:
df2.shape

(500, 10)

In [54]:
df1.describe()

         order_id  customer_rating
count  500.000000       500.000000
mean   250.500000         2.480000
std    144.481833         1.118975
min      1.000000         1.000000
25%    125.750000         1.000000
50%    250.500000         2.500000
75%    375.250000         3.000000
max    500.000000         4.000000

In [55]:
df2.describe()

         order_id    quantity        price   discount         sales
count  500.000000  500.000000   500.000000  500.00000    500.000000
mean   250.500000    4.968000   768.158000    0.14666   3333.059560
std    144.481833    2.569081   404.010497    0.08612   2693.185995
min      1.000000    1.000000    50.000000    0.00000     67.320000
25%    125.750000    3.000000   432.750000    0.08000   1120.867500
50%    250.500000    5.000000   742.000000    0.15000   2582.805000
75%    375.250000    7.000000  1094.500000    0.22000   4998.030000
max    500.000000    9.000000  1499.000000    0.30000  12700.800000

In [57]:

df1['date'] = pd.to_datetime(df1['date'])
df1 = df1.sort_values(by="date")
df1

In [ ]:
df1.isnull().sum()

order_id           0
customer_rating    0
date               0
dtype: int64

In [ ]:
df2.isnull().sum()

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [ ]:
df1.duplicated().sum()

np.int64(0)

In [ ]:
df2.duplicated().sum()

np.int64(0)

In [58]:
df1['date'] = pd.to_datetime(df1['date'])
df1

In [62]:

daily_orders = df1.groupby('date')['order_id'].nunique()
daily_orders

date
2024-01-01    1
2024-01-02    3
2024-01-04    2
2024-01-05    2
2024-01-06    1
             ..
2024-12-22    1
2024-12-24    2
2024-12-25    5
2024-12-29    1
2024-12-30    2
Name: order_id, Length: 267, dtype: int64

In [65]:
# merge df1 and df2 to ensure we have the date column in df1
df1 = df1.merge(df2[['order_id', 'date']])
df1

     order_id  customer_rating     date_x      date_y        date
0         447                3 2024-01-01  2024-01-01  2024-01-01
1         264                4 2024-01-02  2024-01-02  2024-01-02
2         207                1 2024-01-02  2024-01-02  2024-01-02
3          64                1 2024-01-02  2024-01-02  2024-01-02
4         497                4 2024-01-04  2024-01-04  2024-01-04
..        ...              ...        ...         ...         ...
495        63                3 2024-12-25  2024-12-25  2024-12-25
496       252                3 2024-12-25  2024-12-25  2024-12-25
497        38                4 2024-12-29  2024-12-29  2024-12-29
498       313                1 2024-12-30  2024-12-30  2024-12-30
499       420                2 2024-12-30  2024-12-30  2024-12-30

[500 rows x 5 columns]

In [66]:
df1.describe()

         order_id  customer_rating               date_x
count  500.000000       500.000000                  500
mean   250.500000         2.480000  2024-07-04 18:14:24
min      1.000000         1.000000  2024-01-01 00:00:00
25%    125.750000         1.000000  2024-04-11 12:00:00
50%    250.500000         2.500000  2024-07-05 00:00:00
75%    375.250000         3.000000  2024-09-30 06:00:00
max    500.000000         4.000000  2024-12-30 00:00:00
std    144.481833         1.118975                  NaN